version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=true